id: 0b8f54a760cc47afad6435a28443d110
initial_creation_type: ocr
source_metadata:
  volumes:
    1930c935a1cd4f178def9cbe7fbb4fa4:
      base_file: v018.txt
      image_group_id: I1PD95863
      title: སྤྱོད་པ་བསྡུས་པའི་སྒྲོན་མ།
      total_pages: 1634
      volume_number: 18
